[package]
name = "tsm-rust"
version = "0.1.0"
authors = ["Johan le Roux <jleroux99@gmail.com>"]

[dependencies]
piston_window = "0.80.0"
piston2d-opengl_graphics = "0.53.0"
rand = "0.5.4"
num = "0.2.0"
quickersort = "3.0.1"